In [ ]:
import numpy as np


In [ ]:
# Prices in rupees
price = np.array([100, 250, 300, 150, 500])

# Quantities sold
quantity = np.array([3, 1, 4, 2, 1])


In [ ]:
# Element-wise multiplication
total_sale = price * quantity
print("Total Sale per Product:", total_sale)


Total Sale per Product: [ 300  250 1200  300  500]


In [ ]:
total_revenue = np.sum(total_sale)
print("Total Revenue:", total_revenue)


Total Revenue: 2550


In [ ]:
average_sale = np.mean(total_sale)
print("Average Sale per Product:", average_sale)


Average Sale per Product: 510.0


In [ ]:
print("Max Revenue Product:", np.max(total_sale))
print("Min Revenue Product:", np.min(total_sale))

Max Revenue Product: 1200
Min Revenue Product: 250


In [ ]:
discount = 0.10
final_price = price - (price * discount)
print("Final price after 10% discount:", final_price)

# New sale
final_sale = final_price * quantity
print("Final Sale after discount:", final_sale)


Final price after 10% discount: [ 90. 225. 270. 135. 450.]
Final Sale after discount: [ 270.  225. 1080.  270.  450.]


In [ ]:
# Check shapes
print("Shape of price:", price.shape)
print("Shape of quantity:", quantity.shape)

# Reshape to column vector (5,1)
price_reshaped = price.reshape(5, 1)
print("Reshaped Price (5x1):\n", price_reshaped)


Shape of price: (5,)
Shape of quantity: (5,)
Reshaped Price (5x1):
 [[100]
 [250]
 [300]
 [150]
 [500]]


In [ ]:
# Stack all columns horizontally
data = np.column_stack((price, quantity, total_sale, final_sale))
print("Combined data table:\n", data)


Combined data table:
 [[1.00e+02 3.00e+00 3.00e+02 2.70e+02]
 [2.50e+02 1.00e+00 2.50e+02 2.25e+02]
 [3.00e+02 4.00e+00 1.20e+03 1.08e+03]
 [1.50e+02 2.00e+00 3.00e+02 2.70e+02]
 [5.00e+02 1.00e+00 5.00e+02 4.50e+02]]


In [ ]:
# Products with price > 200
print("Prices > 200:", price[price > 200])

# Products where total sale > 300
print("Total sales > 300:", total_sale[total_sale > 300])


Prices > 200: [250 300 500]
Total sales > 300: [1200  500]


In [ ]:
# Introduce missing value
price_with_nan = np.array([100, 250, np.nan, 150, 500])
print("Is NaN present?:", np.isnan(price_with_nan))

# Replace NaN with mean price
mean_price = np.nanmean(price_with_nan)
cleaned_price = np.nan_to_num(price_with_nan, nan=mean_price)
print("Cleaned price array:", cleaned_price)


Is NaN present?: [False False  True False False]
Cleaned price array: [100. 250. 250. 150. 500.]
